// Code generated by "stringer -type LogID"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Norm-0]
	_ = x[Tracy-1]
}

const _LogID_name = "NormTracy"

var _LogID_index = [...]uint8{0, 4, 9}

func (i LogID) String() string {
	if i < 0 || i >= LogID(len(_LogID_index)-1) {
		return "LogID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogID_name[_LogID_index[i]:_LogID_index[i+1]]
}
