// Code generated by "stringer -type SettingKey"; DO NOT EDIT.

package logger

import "testing"

func TestSettingKey_String(t *testing.T) {
	tests := []struct {
		name string
		i    SettingKey
		want string
	}{
		{
			name: "destination",
			i: DestinationSetting,
			want: "DestinationSetting",
		},
		{
			name: "format",
			i: FormatSetting,
			want: "FormatSetting",
		},
		{
			name: "omittime",
			i: OmitTimeSetting,
			want: "OmitTimeSetting",
		},
		{
			name: "whatthe",
			i: 99,
			want: "SettingKey(99)",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("SettingKey.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
